 $(document).ready(function()
    {
        $("#button1").click(function()
        {
            $("#body1").slideToggle("slow");
        });
        $("#button2").click(function()
        {
            $("#body2").slideToggle("slow");
        });
        $("#button3").click(function()
        {
            $("#body3").slideToggle("slow");
        });
        $("#button4").click(function()
        {
            $("#body4").slideToggle("slow");
        });
    });
